### ISSUE TITLE
Kubernetes Ingress Controller Fake Certificate. Not the one which is created with selfsigned

### ISSUE THREAD

**Issue by vyom-soft** [eddycharly/kind-playground#1]
Hello,

I have gone through you wonderful example. The keycloak certificate which I see is fake one, not the one which is self signed created and installed in the cluster.

I am using metallb as LB  &  nginx ingress.

I am not sure why am I not seeing the selfsigned cert. Please can you hint where am I going wrong,

<img width="536" alt="image" src="https://user-images.githubusercontent.com/18686082/218448650-6f10f5ff-3f29-464e-8817-aa22623545cb.png">

```
ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: https
  pathType: ImplementationSpecific
  annotations: {
    cert-manager.io/cluster-issuer: vyomsoft-prod-ca-issuer,
    nginx.ingress.kubernetes.io/proxy-body-size: "25m",
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30",
    nginx.ingress.kubernetes.io/proxy-read-timeout: "20",
    nginx.ingress.kubernetes.io/client-max-body-size: "4",
    nginx.ingress.kubernetes.io/proxy-buffering: "on",
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k",
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "1024m",
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  }
  rules:
    -
      host: keycloak.dev.vyomsoft.devopslab.tech
      paths:
        - path: "/"
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - keycloak.dev.vyomsoft.devopslab.tech
      secretName: vyomsoft-prod-ca-tech

```
 Thank you

**Comment by cmoulliard** [comment]
Workaround is to install the certificate manager, create a ClusterIssuer (= selfsigned) and let the certificate manager to generate the proper TLS secret including ca.crt, tls.crt, tls.key

```
helm repo add jetstack https://charts.jetstack.io
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set installCRDs=true

kubectl delete clusterissuer/selfsigned-issuer
cat <<EOF | kubectl apply -f -
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
EOF
```
Some minor changes are needed to install keycloak
```
helm upgrade --install --wait --timeout 15m \
  --namespace keycloak --create-namespace \
  --repo https://charts.bitnami.com/bitnami keycloak keycloak \
  --reuse-values --values - <<EOF
auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin
  managementUser: manager
  managementPassword: manager
proxy: edge # Needed to avoid https -> http redirect within the browser
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer # To tell to the certificate manager to generate a self signed certificate
  hostname: ${KEYCLOAK_HOSTNAME}
  ingressClassName: nginx
  tls: true
  extraTls:
  - hosts:
    - ${KEYCLOAK_HOSTNAME}
    # Removed the TLS value as cert manager will generate it OOTB and will update the ingress resource
postgresql:
  enabled: true
  auth:
   username: admin
   password: admin
EOF
```
